apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app
  namespace: monitoring
  labels: { release: monitoring }
spec:
  selector:
    matchLabels: { app: demo-app }
  namespaceSelector:
    matchNames: ["default"]
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
